### ISSUE TITLE
Add feat.params setting

### ISSUE THREAD

**Issue by gorinars** [Pankaj-Baranwal/pocketsphinx#2]
Otherwise accuracy is bad

config.set_string('-featparams', path_to_feat.params"))

**Comment by Pankaj-Baranwal** [comment]
But Aren't the feat.params present within the acoustic model?
I see this line in the command window:
``` NFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /home/pankaj/catkin_ws/src/pocketsphinx/demo/cmusphinx-en-in-5.2/en_in.cd_cont_5000/feat.params```

**Comment by gorinars** [comment]
seems like I was wrong with this guess. still, there is some non-deterministic behavior that we should understand
