### ISSUE TITLE
No language model specified?

### ISSUE THREAD

**Issue by arixrobotics** [Pankaj-Baranwal/pocketsphinx#6]
Hi Sir, 
I'm trying to run your example kws demo. 

I launched:
`roslaunch pocketsphinx kws.launch dict:=/home/arifrahman/catkin_ws/src/pocketsphinx/demo/voice_cmd.dic kws:=/home/arifrahman/catkin_ws/src/pocketsphinx/demo/voice_cmd.kwlist
`

But I got error:
`[ERROR] [WallTime: 1512091141.478785] No language model specified. Couldn't find defaut model.
`

The .dic .kwlist files are there in the directory. Can you give some insights why this happens?

**Comment by Pankaj-Baranwal** [comment]
Pocketsphinx couldn't find an acoustic model on your system.  
You need to give it the absolute location of the model. To do this, add another command line argument:  
hmm:= /home/<your_user_name>/Desktop/xiaoyou/tdt_sc_8k

**Comment by arixrobotics** [comment]
Oh. And where can I get this file/folder tdt_sc_8k?

**Comment by Pankaj-Baranwal** [comment]
That's just a sample acoustic model location.
There are models available for a variety of languages which can be found here:
https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/

**Comment by arixrobotics** [comment]
Aha ok will try this.

**Comment by Pankaj-Baranwal** [comment]
Did it work?

**Comment by arixrobotics** [comment]
Ah yes it did. 
Somehow my pocketsphinx installation got into python's folder, so not the default path. 

Thanks!

**Comment by Femi-Tofade** [comment]
Hi,

Having the exact same issues..
How did you solve it? @arixrobotics

**Comment by arixrobotics** [comment]
Sorry @femi-tofade, its been so long I don't remember anything about this.
