### ISSUE TITLE
Voice Recognition

### ISSUE THREAD

**Issue by jasirjasir** [Pankaj-Baranwal/pocketsphinx#8]
Can We use pocketPhinx Library for continuous Voice recognition like amazone Alexa.

**Comment by mdalzin** [comment]
Yes, you could take advantage of hotword listening using keyword mode. I would go check the official documentation at https://cmusphinx.github.io/wiki/tutoriallm/#keyword-lists.

**Comment by Pankaj-Baranwal** [comment]
Yes, you can.  
IF you are using ROS (which this repo depends on), you can run the ```launch/continuous.launch``` of this repo file to use pocketsphinx for "Alexa"-style continuous voice recognition.
