### ISSUE TITLE
No such file or directory: 'testing_audio.wav'

### ISSUE THREAD

**Issue by mdalzin** [Pankaj-Baranwal/pocketsphinx#9]
Running the script and saying each word is working fine, but after the STOP RECORDING message is shown, I get an error at line 236 saying there is no testing_audio.wav file. Earlier, I get the message "sh: rec: command not found", leading me to believe that the file is never created or recorded to. Any insight into what I can do for this? Thanks!

**Comment by Pankaj-Baranwal** [comment]
It would be great if you could provide more information.  
Which script are you running?  
Exact command you executed.  
Also attach the terminal logs.

**Comment by mdalzin** [comment]
Problem solved! It ended up being that I didn't have sox recorder properly updated.
